### ISSUE TITLE
Can't partially remove item from cart.

### ISSUE THREAD

**Issue by rhnonose** [gabiseabra/react-spree-boilerplate#1]
If you add 2 items of the same product to the cart and try to remove just one, it removes the product entirely.

Reproduced on the [demo app](https://react-spree-app.herokuapp.com).

**Comment by gabiseabra** [comment]
The theme is a little confusing. The remove button is a "remove all" for each item, and the inputs are sent automatically onBlur (or when you submit the form like normal) so there's no need to press any buttons.
I should style it to a little inline X button instead of a big red CLICK HERE button.
Thanks for the heads up, I'm going to fix it.
